name: shifts
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  font_awesome_flutter: ^10.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  intl: ^0.18.1
  uuid: ^3.0.7
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.0
  flutter_colorpicker: ^1.0.3
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  shimmer: ^3.0.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.1

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: NothingFont
      fonts:
        - asset: assets/fonts/nothing_font.ttf
